# Generated by Django 2.0.6 on 2019-03-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodfitness',
            name='password',
            field=models.CharField(default='', max_length=900),
        ),
    ]
